"""Modul 1: Das Erz, 1853–1862. Schreibt data/erz.json.

Alle Stellen am Seitenbild gelesen, in den Digitalisaten der Bayerischen Staatsbibliothek
(digitale-sammlungen.de; Bildnummer in Klammern):
- F. W. von Reden, Erwerbs- und Verkehrs-Statistik des Königstaats Preußen, Bd. 2 (Darmstadt 1853),
  S. 1026–1027 (bsb10014001, Bild 224–225).
- C. Hartmann, Der heutige Standpunkt des deutschen Eisenhüttengewerbes (Leipzig 1861), S. 19–20
  (bsb10292897, Bild 35–36).
- Königlich Preußischer Staats-Anzeiger Nr. 229, 28. September 1859, S. [1] (bsb10486476, Bild 571).
- Der Berggeist 5 (1860), S. 487–488 (bsb10705890, Bild 499–500); 6 (1861), S. 138 (bsb10705891,
  Bild 142) und S. 436 (bsb10705892, Bild 18).
- Zeitung des Vereins Deutscher Eisenbahnverwaltungen 2 (1862), S. 350 und 465 (bsb10934031,
  Bild 372 und 485).
- Der Aktionär 9 (1862), S. 612 (bsb10213880, Bild 646).
Schreibung und Zeichensetzung der Drucke; ſ als s; Silbentrennung aufgelöst; Sperrungen nicht
wiedergegeben; Auslassungen […].
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "erz.json"


def u(n, pg, titel, orig, note=""):
    d = {"n": n, "pg": pg, "titel": titel, "orig": orig.strip()}
    if note:
        d["note"] = note
    return d


TAL = [
    u(1, "Reden 1853, S. 1026–1027", "Der Siegkreis um 1850: Kalk, Eisen, ein wenig Gewerbe",
      """Vorzüglichste Erzeugnisse und Erwerbsmittel: Getreide, Wein, Viehzucht, Waldnutzungen, Steinbruchbetrieb, Blei, Eisen, Braunkohlen u. s. w. Haupterwerb des Kreises ist Ackerbau, dessen Ertrag aber, im gebirgigen Theile, hinsichtlich des Rockens und Weizens, sowie der Hülsenfrüchte, nicht einmal das örtliche Bedürfniß befriedigt. […] Großhandel findet sich nicht, der Kleinhandel aber und die sonstigen mit dem Landbau nicht zusammenhängenden Gewerbe, beschränken sich auf den nächsten und nothwendigsten Bedarf (etwa die Städte ausgenommen) und werden häufig nur als Nebengeschäft betrieben. Die bedeutendsten Anlagen für veredelnde Erwerbthätigkeit sind. 1 Vitriolfabrik zu Rott mit etwa 25 Arbeitern und 3500 Ztr. jährlicher Erzeugung; die Friedrich-Wilhelm Eisenhütte zu Menden mit ungefähr 200 Berg- und Hüttenarbeitern und der Steinkohle als Feuerungsstoff; 1 Stärkefabrik zu Hennef mit 10 Arbeitern; 1 Fabrik von wollenen Stuhl- und gedruckten Waaren zu Pingsfeld (?) mit 50 Arbeitern; 1 Alaunfabrik zu Spich mit 45 Arbeitern; 10 Kalkbrennereien in der Bürgermeisterei Ruppichteroth; 1 Eisenhütte bei Ruppichteroth; der Bergbau einer französischen Gesellschaft in der Gegend von Blankenberg, welche, vor etwa 10 Jahren und seitdem, an 100 (theils neue, theils vielfach vorhandene, alte, verlassene) Erzgruben in Betrieb gesetzt hat und dadurch mehrere hundert Arbeiter beschäftigt, auch entsprechende Hüttenanlagen gemacht hat; […]""",
      "Eine amtliche Statistik von 1853, kurz bevor von einer Bahn die Rede ist. Das Bröltal ist ein Bauernland, in dem das Getreide nicht einmal für die eigenen Leute reicht; dazwischen Kalköfen und eine Eisenhütte bei Ruppichteroth. Mit der „Friedrich-Wilhelm Eisenhütte zu Menden“ ist wohl die Friedrich-Wilhelms-Hütte bei Troisdorf gemeint, die in den folgenden Einheiten die Bahn will (Plan [3]). „Ztr.“ ist der Zentner zu 100 Pfund; „Rocken“ ist Roggen; das Fragezeichen bei Pingsfeld steht im Druck."),
    u(2, "Hartmann 1861, S. 19–20", "Brauneisenstein zwischen Agger und Bröl",
      """In dem Gebiete des Lenneschiefers besitzen diese Lagerstätten besonders auf den darin auftretenden Kalksteinlagern einen größeren Zusammenhang und nähern sich einer bestimmten Lagerform, sind dabei auf einzelne Bezirke beschränkt, schwanken zwischen eigentlichen Lagern, welche den Lenneschiefern angehören, und einer jüngeren, tertiären, in Mulden des Kalkes abgelagerten Bildung; der Brauneisenstein ist manganhaltig von vorzüglicher Beschaffenheit. Dieses Vorkommen ist besonders ausgebildet im Kreise Gummersbach, Regierungsbezirk Cöln, zwischen der Agger und Broel, wie in der Partie von Markengötz über Bonig, Bandenberg, Forst und Oberkaltenbach, 1½ Meile lang bis zu ½ Meile breit; in der nahe daran liegenden Partie von Linden über Elsenroth, Bierenbach und Ruppichteroth ¾ Meilen lang; und im Siegkreise bei Ruppichteroth, Dehleroth und Saurenbach, von wo aus sie dem Laufe des Broelbaches folgend bis in die Gegend von Waldbroel reicht.""",
      "Ein Fachbuch über die deutsche Eisenindustrie zählt die Erzlager auf. Brauneisenstein auf Kalk: Erz und Zuschlag liegen im Bröltal beieinander, und das Lager folgt dem Bach. Eine preußische Meile sind etwa 7,5 Kilometer. Die Ortsnamen stehen in der Schreibung des Drucks („Bonig“, „Dehleroth“); Saurenbach ist das Tal, in das die erste Zweigbahn führte (Anleihe [3])."),
]

STRASSE = [
    u(1, "Staats-Anzeiger, 28.9.1859", "Der Erlass vom 4. September 1859: die Brölstraße",
      """Allerhöchster Erlaß vom 4. September 1859 — betreffend die Verleihung der fiskalischen Vorrechte für den Bau und die Unterhaltung einer Gemeinde-Chaussee durch das Broelthal, von Waldbroel über Ruppichteroth nach Allner, im Kreise Siegburg, der sogenannten Broelstraße.

Nachdem Ich durch Meinen Erlaß vom heutigen Tage den Bau einer Gemeinde-Chaussee durch das Broelthal, von Waldbroel über Ruppichteroth nach Allner, im Kreise Siegburg, der sogenannten Broelstraße, genehmigt habe, bestimme Ich hierdurch, daß das Expropriationsrecht für die zu der Chaussee erforderlichen Grundstücke, imgleichen das Recht zur Entnahme der Chaussee-Bau- und Unterhaltungs-Materialien, nach Maaßgabe der für die Staats-Chausseen bestehenden Vorschriften, auf diese Straße zur Anwendung kommen sollen. Zugleich will Ich den betheiligten Gemeinden gegen Uebernahme der künftigen chausseemäßigen Unterhaltung der Straße, das Recht zur Erhebung des Chausseegeldes nach den Bestimmungen des für die Staatschausseen jedesmal geltenden Chausseegeld-Tarifs, einschließlich der in demselben enthaltenen Bestimmungen über die Befreiungen, so wie der sonstigen, die Erhebung betreffenden zusätzlichen Vorschriften, wie diese Bestimmungen auf den Staats-Chausseen von Ihnen angewandt werden, hierdurch verleihen. Auch sollen die dem Chausseegeld-Tarife vom 29. Februar 1840 angehängten Bestimmungen wegen der Chaussee-Polizei-Vergehen auf die gedachte Straße zur Anwendung kommen. Der gegenwärtige Erlaß ist durch die Gesetz-Sammlung zur öffentlichen Kenntniß zu bringen.
Ostende, den 4. September 1859.
Im Namen Sr. Majestät des Königs:
Wilhelm, Prinz von Preußen, Regent.
von der Heydt. von Patow.
An den Minister für Handel, Gewerbe und öffentliche Arbeiten und den Finanz-Minister.""",
      "Am Anfang steht keine Bahn, sondern eine Straße. Die Gemeinden bauen eine Chaussee durch das Tal; der Staat gibt ihnen das Recht zu enteignen und Chausseegeld zu erheben. Auf dieser Straße, genauer auf ihrem Planum, wird die Bahn liegen (Plan [2]). Der Erlass stand in der Gesetzsammlung und in den Amtsblättern aller preußischen Regierungen; hier nach dem Staats-Anzeiger. Wilhelm, Prinz von Preußen, regierte seit 1858 für seinen kranken Bruder. Allner liegt an der Sieg bei Hennef."),
    u(2, "Berggeist 6 (1861), S. 138", "Ende 1860: eine Hüttenbahn bei Troisdorf, die Straße fertig, die Bahn noch nicht",
      """In ziemlich lebhaftem Betriebe war die Friedrich-Wilhelmshütte bei Siegburg, welche durch eine auf dem Communalwege erbaute, schmalspurige Pferde-Eisenbahn sich mit der Haltestelle Troisdorf der Deutz-Giessener Bahn in Verbindung setzte. Für den dortigen Hohofen sind ca. 4000 Wagen Siegen'schen Eisensteins angekauft worden, die jedoch erst im laufenden Jahr zur Anfuhr kommen. Die Hohöfen im Revier Oberberg lagen, ebenso wie der Ruppichterother Hohofen, kalt, die Puddelwerke zu Ründeroth, Oberwiehl etc. waren im schwachen Betriebe, während die Haardter Alaunhütten in bisheriger Weise und Ausdehnung fortarbeiteten.

Die Broelstrasse von Allner über Ruppichteroth bis Waldbroel ist fertig gestellt, die projectirte Pferdeeisenbahn auf derselben aber noch nicht in Angriff genommen worden.""",
      "Aus einem Bericht über „Berg- und Hüttenwesen im Rheinischen Hauptbergdistrict während des letzten Trimesters 1860“, Abschnitt Regierungsbezirk Köln. Zwei Dinge fallen auf: Die Friedrich-Wilhelms-Hütte hatte schon eine eigene schmalspurige Pferdebahn auf einem Gemeindeweg zur Bahnstation Troisdorf, das Muster für die Brölbahn. Und der Hochofen bei Ruppichteroth stand kalt. Die Straße ist Ende 1860 fertig, mit der Bahn ist noch nicht begonnen worden."),
]

PLAN = [
    u(1, "Berggeist 5 (1860), S. 487", "„Eine neue Aera“: Kalk für 5 statt 18 Silbergroschen",
      """Von der Sieg, 21. Juli. [Brölthaler Eisenbahn und ihr Einfluss auf die Gewerbthätigkeit.] Die Brölthaler Eisenbahn, d. h. die Pferdebahn, welche durch die eifrige und umsichtige Initiative der Direction des Sieg-Rheinischen Bergwerks- und Hütten-Actienvereins und durch das Entgegenkommen der Behörden und Gemeinden eben zum Abschluss gekommen, ist ohne Zweifel berufen, nicht allein für das ebengedachte Etablissement, sondern, was wichtiger, für die Landwirthschaft und für die bestehenden und werdenden Gruben- und Hüttenbetriebe eines weiten Umkreises eine neue Aera herbeizuführen. Man wird sofort ermessen, dass es sich hier nicht von subjectiven Ansichten und Hoffnungen, vielmehr von einer folgenreichen Thatsache handelt, wenn wir bemerken, dass durch die fragliche Schienenbahn die Transportkosten für das Product der unerschöpflichen Kalksteinbrüche bei Ruppichteroth sich von 15 bis 18 Sgr. auf 5 Sgr. pro 1000 Pfd. ermässigen. Der erstere Satz ist derjenige, welcher nach Fertigstellung der augenblicklich im Bau begriffenen Brölstrasse zu erwarten steht; der letztere ist der für die Pferdebahn in Aussicht genommene. Gleicher Transportvortheil wird selbstverständlich den Eisenerzen zu Theil, womit der Anfangspunct der Bahnlinie „Ruppichteroth“ in so reichem Maasse gesegnet ist.""",
      "Der wichtigste Text des Moduls: ein Bericht in einer Fachzeitung für Bergbau und Hüttenwesen, geschrieben, als der Plan „eben zum Abschluss gekommen“ war. Die Initiative nennt er beim Sieg-Rheinischen Bergwerks- und Hütten-Actienverein, dem die Friedrich-Wilhelms-Hütte gehörte; die neuere Literatur nennt als Träger die Kommanditgesellschaft Friedlieb Gustorff & Co. von 1860 (Plan [2]: „Das Unternehmen tritt als Commandite in sofortiges Leben“). Ein Silbergroschen (Sgr.) war ein Dreißigstel Taler; 1000 Pfund sind zehn Zentner. Die Rechnung des Artikels: Auf der neuen Straße kostet die Fuhre 15 bis 18 Silbergroschen, auf der Bahn 5."),
    u(2, "Berggeist 5 (1860), S. 487", "Auf dem Planum der Chaussee: 75 000 Taler, eine mäßige Dividende",
      """Die Sicherung dieses Unternehmens ist nur dadurch in so vollkommener Vortheilhaftigkeit möglich geworden, dass die Gemeinden, in richtiger Würdigung der voraussichtlichen localen und allgemeinen Vortheile, der Eisenbahn den Bau auf dem Planum selbst der obengedachten Chaussé gestateten.

Die Gesammtanlagekosten der ca. 2½ Meilen messenden Eisenbahn mit einer Spurweite von 2 bis 2½ Fuss sollen sich demnach nur belaufen auf 65,000 Thlr.
die Waggons auf 10,000 „
so dass ein Capital von 75,000 „
aufzubringen ist.

Das Unternehmen tritt als Commandite in sofortiges Leben, da der grössere Theil des Capitals bereits durch die nächsten Interessenten gezeichnet ward.

Wir begrüssen als einen erwünschten, die Gemeinnützlichkeit des Unternehmens gewährleistenden Umstand, die von der kgl. Regierung zu Köln festgehaltene Anforderung „dass der Tarif der Bahn in Anbetracht, dass die Gemeinden ihr Chaussé-Planum unentgeltlich hergeben, so zu normiren sei, dass jenes Transportunternehmen den Unternehmern nicht gerade ein besonderes lucratives Geschäft abgebe, wohl aber Verzinsung, Amortisation und als Aequivalent für das zu übernehmende Risico eine mässige Dividende abwerfe.“ Es soll demnach die Verzinsung zu 5 %, die Amortisation zu 10 %, eine Dividende bis zu 2½ % in Aussicht genommen werden, während ein weiterer Ertrag zur Bildung eines Reservefonds dienen würde. Ueberdies ist nach erfolgter Amortisation eine Verminderung der schon billigen Tarifsätze beaussichtigt. Die Transportgesellschaft übernimmt zudem den Bau einer Siegbrücke bei Allner mit steinernen Pfeilern und Oberbau von Eichenholz und übergibt dieselbe dem freien Verkehr.""",
      "Hier steht der Handel, auf dem die Bahn beruht: Die Gemeinden geben ihr Straßenplanum umsonst, dafür begrenzt die Regierung zu Köln den Gewinn. Die Bahn soll kein „lucratives Geschäft“ sein, sondern Zinsen, Tilgung und eine mäßige Dividende bringen. Diese Bedingung ist der Kern des Begleitspiels. Zwei bis zweieinhalb preußische Fuß sind etwa 63 bis 78 Zentimeter; gebaut wurde die Bahn nach der neueren Literatur mit 785 Millimetern. „gestateten“ und „beaussichtigt“ stehen so im Druck (gestatteten, beabsichtigt); ebenso die Tilgung „zu 10 %“."),
    u(3, "Berggeist 5 (1860), S. 487", "Für wen die Bahn sich lohnt: Kalk, Hütten, Erz",
      """Nachdem wir in Vorstehendem in allgemeinen Umrissen Kenntniss des ohne Zweifel folgenreichen Unternehmens gegeben, wollen wir noch einige specielle Nachrichten folgen lassen. Zunächst ist die früher in diesem Maasse ungeahnte Verwohlfeilung des in reichen Ablagerungen vorhandenen Ruppichterother Kalksteins, dieses für die Landwirthschaft unentbehrlichen Hülfsmittels, von grosser Tragweite für die weite Umgegend. Der Mainzer Kalk kostet gegenwärtig loco Hennef 28 Sgr., der Gladbacher mittels der Köln-Giessener Eisenbahn bezogen 27 Sgr., der Ruppichterother Kalk durch die fragliche Pferdebahn bezogen wird nur 8 Sgr. kosten pro 1000 Pfd. Die billigere Benutzung des Ruppichterother anstatt des Mainzer Kalkes zu Mauerwerken kommt ausserdem in Betracht.

Von nicht minderer Wichtigkeit aber wird die Brölthaler Eisenbahn für die einschlägigen bergbaulichen Interessen und insbesondere für die Eisenindustrie sein. Zunächst für die Ruppichterother Hütte, welche billige Steinkohlen beziehen und ihre Producte billiger versenden kann, dann in erheblichster Weise wichtig für die Friedrich-Wilhelms-Hütte bei Siegburg, unweit des mehrgedachten Endpunctes Hennef. Dieses Etablissement bedient sich zum Hohofenbetriebe bisher des Mainzer und Gladbacher Kalksteins, wird also auf die ca. 120,000 Ctr. seines Hohofenbedarfs einer beträchtlichen, die Concurrenzfähigkeit erhöhenden, Ersparniss theilhaftig. Der Vortheil verdoppelt sich zunächst durch die Herstellung eines zweiten Hohofens, wozu ausserdem die durch die Brölthaler Eisenbahn von 15 auf 5 Sgr. pro 1000 Pfd. sich verwohlfeilenden Transportkosten der Eisenerze auffordert, die das Etablissement bei Ruppichteroth besitzt. Dem beträchtlichen sonstigen dortigen Eisenstein-Grubenbesitze kommen natürlich dieselben Transportvortheile zu Statten und es führen diese ohne Zweifel nunmehr zu einer Verhüttung der vortrefflichen Erze entweder am Fundorte selbst oder, bei der so bedeutend ermässigten Kalk- und Eisensteinfracht, am Zielpunct der Pferdebahn: Hennef, zugleich Station der Köln-Giessener Eisenbahn.""",
      "Kalk zuerst, Erz danach: Der Artikel rechnet die Bahn zuerst über den Kalk, als Dünger für die Landwirtschaft und als Zuschlag für die Hochöfen, die bisher Kalk aus Mainz und Gladbach brauchten. Das Erz bei Ruppichteroth gehört der Hütte selbst („das Etablissement bei Ruppichteroth“). Der zweite Hochofen, von dem hier die Rede ist, ging 1862 in Betrieb (Anleihe [4]). „loco Hennef“ heißt: in Hennef geliefert."),
    u(4, "Berggeist 5 (1860), S. 487–488", "„Die Solidarität ihrer Interessen“",
      """Wir glauben überhaupt nicht zu irren, wenn wir der nächsten Umgebung von Hennef in Folge der Brölthaler Pferdebahn eine lebhafte Zukunft prognosticiren: so dürften z. B. bei dem so billig nach Hennef gelegten Kalkzuschlag, — der überdies 6—8 % Eisen enthält — die unweit der Station Hennef verbreiteten vortrefflichen Sphärosiderite der Braunkohlenformation mit weit grösserm Vortheil daselbst verhüttet, als weiterhin verfahren werden. Wenn die wesentlichen Bedingungen der Prosperität der Eisenindustrie, welche so enorme Massen bewegt, in der billigen Herbeischaffung der Rohstoffe liegen, so sind jenem Orte, was Hohofenanlagen betrifft, von nun an namhafte Vorzüge zugefallen.

Doch auch die sonstigen Hüttenwerke der obern Sieg werden sich theilweise mit Vortheil des billigen Ruppichterother Kalksteins bedienen, so dass den Eisenstein-Versendungen, welche der Ueberfluss des Siegener Landes erwarten lässt, nützliche Betourfrachten zu Statten kämen.

Indem wir in Obigem die weittragende Wichtigkeit der Brölthaler Pferdebahn für die Landwirthschaft und Industrie eines umfangreichen Gebietes im „Berggeist“ zur Besprechung bringen, hoffen wir dazu beizutragen, dass, wo ähnliche Verhältnisse gegeben sind, ähnliche Anlagen aus dem Zusammenwirken der Gemeinden und Industriellen hervorgehen mögen. Was uns England gegenüber lähmt, sind nächst der immerhin grössern Abgabenlast, zumeist die theuern Massentransporte. Landwirthschaft und Eisenindustrie werden beiderseitig gewinnen, wenn sie, wie in oben berichtetem Falle, mehr und mehr die Solidarität ihrer Interessen erkennend, sich zu gemeinsamen Bestrebungen die Hand reichen, anstatt sich um unfruchtbare Theorien zu streiten. Die Gemeinden aber, welche die Brölthaler Eisenbahn fördern, werden, dessen sind wir gewiss, in nicht langen Jahren in dem gestiegenen Werth ihrer Producte und ihres Bodens die gebührende Vergeltung eines verständigen Entgegenkommens finden.""",
      "Der Schluss des Artikels ist ein Programm: Gemeinden und Industrie sollen zusammenarbeiten, wie im Bröltal, damit Deutschland gegen England bestehen kann. Das Versprechen an die Gemeinden, ihr Land werde mehr wert, ist das, woran sich das Spiel messen lässt. „Sphärosiderit“ ist ein knolliges Eisenerz aus den Braunkohlenschichten; „Betourfrachten“ sind Rückfrachten. „als weiterhin verfahren“ heißt: als weiter wegtransportiert."),
]

GELD = [
    u(1, "Berggeist 6 (1861), S. 436", "Juli 1861: eine Anleihe von 300 000 Talern",
      """Köln, 10. Juli. Vom Sieg-Rheinischen Bergwerks- und Hütten-Actienverein ist die Aufnahme einer 5pctigen Anleihe im Betrage von 300,000 Thlr. beschlossen, die zum Course von 85% emittirt wird. Aus dem dieserhalb erlassenen Circular entnehmen wir einige Modalitäten. Bau einer Eisenbahn von der Köln-Giessener Bahn bei Hennef bis nach Ruppichteroth nebst Seitenlinie, Fertigstellung des zweiten Hohofens und Anlage von Cokesöfen, endlich die Verstärkung des Betriebsfonds überhaupt haben die Anleihe nothwendig gemacht. Die Obligationen werden zu 200 Thlr. ausgestellt und ihnen für die nächsten 10 Jahre 10 Zins-Coupons, jeder von 10 Thlr., zahlbar am 1. Juli, beigegeben. Zur Tilgung der Schuld werden vom Jahr 1865 ab jährlich 2% vom Capitalbetrag zurückgezahlt. Der Verein darf weder Actien creiren noch neue Darlehn aufnehmen, denen irgend ein Vorzugsrecht gegen die gegenwärtige Anleihe eingeräumt wird. Das Vorrecht bei der Betheiligung an der Anleihe haben bis zum 20 d. die Actionaire der Gesellschaft.""",
      "Ein Jahr nach dem Plan: Die Hüttengesellschaft leiht sich Geld, unter anderem für den Bau der Bahn „nebst Seitenlinie“, der Zweigbahn ins Saurenbacher Tal (Anleihe [3]). Die Anleihe wird zu 85 Prozent ausgegeben: Wer 200 Taler Schuld zeichnete, zahlte 170 und bekam zehn Taler Zins im Jahr. Wie die Kommanditgesellschaft der Bahn und die Hüttengesellschaft im Einzelnen zusammenhingen, sagen diese Texte nicht."),
    u(2, "ZVDEV 2 (1862), S. 350", "April 1862: „nahezu vollendet“",
      """Pferdebahn von Hennef nach Ruppichteroth. Die im vorigen Jahre begonnene Pferdebahn von der Cöln-Giessener Bahnstation Hennef durch das Brölthal nach Ruppichteroth, durch welche die im und am genannten Thale befindlichen Bergwerke mit den Rheinischen Hüttenwerken und speciell mit der Friedrich-Wilhelmshütte bei Troisdorf in Verbindung gebracht werden sollen, ist nahezu vollendet und dürfte in 1—2 Monaten dem Betrieb übergeben werden können.""",
      "Die Zeitung des Vereins Deutscher Eisenbahnverwaltungen war das Fachblatt der Bahngesellschaften; die Meldung steht neben einer vom 25. April 1862. Begonnen wurde demnach 1861, nach dem Bericht über Ende 1860, in dem die Bahn „noch nicht in Angriff genommen“ war (Straße [2])."),
    u(3, "ZVDEV 2 (1862), S. 465", "Juni 1862: der Betrieb beginnt",
      """Bröhlthaler Kohlen-Eisenbahn in Hennef. Nach dem Berichte, welcher der in den letzten Tagen des Monat Mai abgehaltenen General-Versammlung über den Stand des Unternehmens vorgelegt wurde, ist zu erwarten, dass in wenigen Tagen der Betrieb auf dem Haupttheil der Bahn bereits eröffnet ist. Das Geleise ist nämlich vom Anfangspuncte der Bröhlstrasse bis einige 100 Ruthen oberhalb Schönenberg fertig und ebenso die Zweigbahn im Niedersaurenbacher Thale und einer der Stränge des Bahnhofs bei Warth, welche die Ueberladung von den Wagen der Bahn auf diejenigen der Cöln-Giessener Bahn und umgekehrt vermitteln werden. Zu den unmittelbar daneben zu legenden grossen Zweigsträngen für Wagen der Cöln-Giessener Bahn ist die Weiche aus deren Hauptgeleise gelegt und die Vorkehrungen zur Ausführung dieser Stränge, welche durch die Arbeiter jener Bahn geschieht, sind getroffen. Sobald diese Stränge liegen, wird die Beförderung von Gütern zwischen Hennef, Schönenberg und dem Niedersaurenbacher Thale beginnen. Von verschiedenen Industriellen sind Anträge ergangen, um durch Anschlüsse von Weichen und Zweigsträngen directe Befrachtungen der Bahn zuzuführen. Die Fortführung des Geleises nach Ruppichteroth wird unausgesetzt betrieben, und darf angenommen werden, dass die Bahn die grössere Masse von Gütern von Schönenberg und dem Saurenbacher Thale erhalten werde.

In Betreff der Prosperität des Unternehmens gestalten sich die Aussichten ganz erfreulich, für Hennef sind eine hinlängliche Anzahl Kalköfen projectirt und der Haupt-Interessent, die Friedrich-Wilhelms-Hütte, setzt ehestens einen zweiten Hochofen in Betrieb.""",
      "Die Bahn heißt hier „Bröhlthaler Kohlen-Eisenbahn“: Talaufwärts sollte sie Kohle bringen, talabwärts Erz und Kalk. Eröffnet wird zuerst der Teil bis oberhalb Schönenberg und die Zweigbahn ins Niedersaurenbacher Tal; nach Ruppichteroth wird noch gebaut. Die neuere Literatur nennt den 27. Mai 1862 als Eröffnungstag; nach dieser Meldung vom Juni stand die Eröffnung noch bevor. In Warth bei Hennef wurde von der schmalen Spur auf die Wagen der Staatsbahn umgeladen. Eine Rute waren knapp vier Meter. Die Schreibung „Bröhl-“ ist in diesen Jahren häufig; sie ist nicht mit dem Brohltal bei Andernach zu verwechseln."),
    u(4, "Aktionär 9 (1862), S. 612", "Herbst 1862: „mit andern Etablissements ebenbürtig“",
      """Der am 27. v. M. abgehaltenen Gen.-Vers des Sieg-Rheinischen Bergwerks-Vereins haben wir bereits in Nr. 459 gedacht, wir geben hier aus dem über den Betrieb erstatteten Jaresbericht nachträglich im kurzen Auszug die wesentlichen Daten: An Herdguss und Roheisen wurden im verflossenen Geschäftsjare 14,714,715 Pfd. im Werthe von Thlr. 215,598 produzirt. Gegen die beiden Vorjare hat sich die Produktion um 9 resp. 24% gesteigert. […] Ein zweiter Hochofen ist in Betrieb getreten, auch wurden die Anlagen zur Kokesbereitung bedeutend verstärkt. Von Wichtigkeit für den Gang des Betriebes ist die Eröffnung der Pferdebahn ins Broelthal, sowie die Erklärung der Station Troisdorf der Deutz-Giessener Bahn in der Nähe des Werkes zur allgemeinen Station, wodurch der begünstigte Ausnametarif für Eisenstein- und Roheisen-Transporte auch für diese Station Anwendung fand. Dadurch ist das Werk in den grösseren Verkehr hineingerückt und mit andern Etablissements ebenbürtig geworden.""",
      "Aus den „Rheinisch-Westfälischen Briefen“ des Frankfurter Börsenblatts, datiert „Vom Rhein, 23. Oktbr.“. Die Generalversammlung war am 27. September 1862. Der Name ist hier verkürzt; gemeint ist nach Hochofen, Gießerei, Maschinenfabrik, Walzwerk und Station Troisdorf der Sieg-Rheinische Bergwerks- und Hütten-Actienverein mit der Friedrich-Wilhelms-Hütte. Die Zeichen für Pfund und Taler sind aufgelöst; ausgelassen sind Zahlen zu Gießerei, Maschinenfabrik und Walzwerk. Für die Hütte war die Bahn eine von zwei Verbesserungen im Verkehr, nicht die einzige."),
]

SECS = [
    ("tal", "Das Tal vor der Bahn", "Tal", TAL,
     "Bauernland mit Kalköfen und einer kleinen Eisenhütte, darunter Brauneisenstein von vorzüglicher Beschaffenheit: das Bröltal in einer Statistik von 1853 und einem Fachbuch von 1861."),
    ("strasse", "Erst die Straße", "Straße", STRASSE,
     "1859 genehmigt der Staat den Gemeinden eine Chaussee durch das Bröltal. Ende 1860 ist sie fertig; die Pferdebahn, die auf ihr liegen soll, ist noch nicht begonnen."),
    ("plan", "Der Plan von 1860", "Plan", PLAN,
     "Ein Bericht im „Berggeist“ vom Juli 1860, vollständig: was die Bahn kosten soll, wer sie bezahlt, was die Regierung zu Köln verlangt, und für wen sie sich lohnen wird."),
    ("geld", "Geld und Eröffnung, 1861–1862", "Anleihe", GELD,
     "Eine Anleihe der Hüttengesellschaft, zwei Meldungen der Eisenbahn-Fachzeitung und ein Jahresbericht: Im Sommer 1862 fährt die Bahn."),
]

DATA = {
    "id": "erz",
    "titel": "Das Erz, 1853–1862",
    "autor": "Amtliche Statistik, Fachzeitschriften für Berg- und Hüttenwesen, Eisenbahn und Börse",
    "jahr": "1853–1862",
    "sprache": "de",
    "orig_sprache": "de",
    "pg_label": "",
    "quelle": "F. W. von Reden, Erwerbs- und Verkehrs-Statistik des Königstaats Preußen, Bd. 2 (Darmstadt 1853); C. Hartmann, Der heutige Standpunkt des deutschen Eisenhüttengewerbes (Leipzig 1861); Königlich Preußischer Staats-Anzeiger 1859; Der Berggeist. Zeitung für Berg-, Hüttenwesen und Industrie 5 (1860) und 6 (1861); Zeitung des Vereins Deutscher Eisenbahnverwaltungen 2 (1862); Der Aktionär 9 (1862). Alle gelesen an den Digitalisaten der Bayerischen Staatsbibliothek (digitale-sammlungen.de).",
    "hinweis": "Die Vorgeschichte der Bahn in den Stimmen ihrer Zeit: einer amtlichen Statistik, eines Fachbuchs, eines königlichen Erlasses und der Fachpresse für Bergbau, Eisenbahn und Börse. Die Lokalzeitungen des Siegkreises sind aus den Vereinigten Staaten nicht zugänglich; ihre Stelle vertreten hier die überregionalen Blätter. Text nach den Drucken, an den Seitenbildern gelesen; Schreibung und Zeichensetzung wie gedruckt, ſ als s, Silbentrennung aufgelöst, Sperrungen nicht wiedergegeben, Auslassungen mit […] bezeichnet. Die Seitenangaben nennen die Quelle in Kurzform.",
    "sections": [{"id": i, "titel": t, "zk": zk, "blurb": b, "units": us} for i, t, zk, us, b in SECS],
}

if __name__ == "__main__":
    for s in DATA["sections"]:
        ns = [x["n"] for x in s["units"]]
        assert ns == list(range(1, len(ns) + 1)), (s["id"], ns)
    OUT.write_text(json.dumps(DATA, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print("ok", OUT.name, sum(len(s["units"]) for s in DATA["sections"]), "units")
